### ISSUE TITLE
好像没有日期格式化函数

### ISSUE THREAD

**Issue by phpyii** [tnfe/bbo#6]
比如把时间戳格式化成年月日   yyyy-mm-dd

**Comment by hrout** [comment]
可以使用bbo.formatDuration。
`bbo.formatDuration(34325055574);  // => '397 days, 6 hours, 44 minutes, 15 seconds, 574 milliseconds'`
业务实际中，日期处理类业务也比较复杂，bbo计划做一些简单的扩展。
如果涉及到国际化等业务场景，可以参看https://momentjs.com/
