### ISSUE TITLE
函数名规范不够统一

### ISSUE THREAD

**Issue by Xiaoleng123** [tnfe/bbo#7]
isiPhone、isIPad、isIphoneXmodel，ip这两个字母的大小写不一致，原则上iPhone在组成词汇时，i使用大写，如isIPhone

**Comment by ilgei** [comment]
> isiPhone、isIPad、isIphoneXmodel，ip这两个字母的大小写不一致，原则上iPhone在组成词汇时，i使用大写，如isIPhone

木问题，建议接纳。
